services:
  ipfs:
    image: ipfs/kubo
    container_name: ipfs
    expose:
      - "5001"
      - "8080"
    networks:
      - internal_net

  brenthy:
    image: local/brenthy
    container_name: brenthy
    expose:
      - "29200"
      - "29201"
      - "29202"
    networks:
      - internal_net
    environment:
      - PY_IPFS_HTTP_CLIENT_DEFAULT_ADDR=/dns/ipfs/tcp/5001/http
      - BRENTHY_API_IP_LISTEN_ADDRESS=0.0.0.0  # listen on all IP interfaces

networks:
  internal_net:
    driver: bridge
